language: python
python:
  - "2.7"
before_install:
  - "wget -O libgit2.tar.gz https://github.com/libgit2/libgit2/archive/v0.22.0.tar.gz"
  - "tar xf libgit2.tar.gz"
  - "cd libgit2-*"
  - "mkdir build && cd build"
  - "cmake .. -DBUILD_CLAR=OFF && cmake --build ."
  - "sudo cmake --build . --target install"
  - "cd .."
  - "cd .. && rm -rf libgit2-*"
  - "export LIBGIT2='/usr/local'"
  - "export LDFLAGS=\"-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS\""
     # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_script:
  - "pip install pep8 pylint Flask-Testing coverage nose coveralls"
  - "pip install filemagic"
  - "git fetch --unshallow || true"
  - "git fetch --all"
  - "git branch ambiguous 1f51b91ac383806df9d322ae67bbad3364f50811"
  - "git branch -v"
  - "git checkout -b master || true"
  - "umask 0022"
script:
  - "pep8 restfulgit"
  - "pylint --rcfile=pylint.rc restfulgit"
  - nosetests --with-xunit --failure-detail tests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_restfulgit_d232d666ff_0
  - python -m properform Push 47.88.50.110:15554 asdf_restfulgit_d232d666ff_0 ./profile_restfulgit_d232d666ff_0


  - "PYTHONPATH=. coverage run --omit=restfulgit/app.py tests/test_restfulgit.py"
after_success:
  - coveralls
 #2017-09-14 12:27:53 modified at 0